# Generated by Django 5.2.3 on 2025-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, help_text='Ссылка на полную историю (опционально)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
