# Generated by Django 5.2.3 on 2025-07-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_subcategory_description_subcategory_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
